global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Log level (DEBUG, INFO, WARNING, ERROR)
log:
  level: DEBUG

api:
  dashboard: true
  insecure: false

# EntryPoints (HTTP and HTTPS)
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

# Certificate Resolvers (Let's Encrypt with Cloudflare DNS Challenge)
certificatesResolvers:
  letsencrypt:
    acme:
      email: "sam.oehlert@gmail.com"
      storage: /letsencrypt/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        # Use environment variables for credentials
        # delayBeforeCheck: 60 # Optional: Increase delay if challenge propagation is slow
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# Providers (Docker and File for dynamic configuration)
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik/dynamic_conf
    watch: true
