http:
  middlewares:
    securityHeaders:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        stsSeconds: 31536000 # 1 year HSTS
        stsIncludeSubdomains: true
        stsPreload: true

  routers:
    proxmox-rtr:
      rule: "Host(`prox.soehlert.com`)"
      entryPoints:
        - websecure
      service: proxmox-svc
    homepage-rtr:
      rule: "Host(`homepage.soehlert.com`)"
      entryPoints:
        - websecure
      service: homepage-svc
    unifi-rtr:
      rule: "Host(`unifi.soehlert.com`)"
      entryPoints:
        - websecure
      service: unifi-svc
    pihole1-rtr:
      rule: "Host(`pihole1.soehlert.com`)"
      entrypoints:
        - websecure
      service: pihole1-svc

  services:
    proxmox-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.2.21:8006"
        passHostHeader: true
        serversTransport: insecure-transport
    homepage-svc:
      loadbalancer:
        servers:
          - url: "http://192.168.2.31:3000"
    unifi-svc:
      loadbalancer:
        servers:
          - url: "https://192.168.2.43:8443"
        serversTransport: insecure-transport
    pihole1-svc:
      loadbalancer:
        servers:
          - url: "http://192.168.2.42/admin"

  serversTransports:
    insecure-transport:
      insecureSkipVerify: true

