global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: "http://prometheus-influxdb-connector:9201/write"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']
    metrics_path: '/metrics'
